<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Tipos de Documentos de Identificación (CAT-022 MH)
        $documentos = [
            ['ID_TIPODOCUMENTO' => 1, 'CODIGO_MH' => '13', 'NOMBREDOCUMENTO' => 'DUI (Documento Único de Identidad)', 'MASCARA_FORMATO' => '00000000-0', 'ESACTIVO' => true],
            ['ID_TIPODOCUMENTO' => 2, 'CODIGO_MH' => '36', 'NOMBREDOCUMENTO' => 'NIT (Número de Identificación Tributaria)', 'MASCARA_FORMATO' => '0000-000000-000-0', 'ESACTIVO' => true],
            ['ID_TIPODOCUMENTO' => 3, 'CODIGO_MH' => '03', 'NOMBREDOCUMENTO' => 'Pasaporte', 'MASCARA_FORMATO' => null, 'ESACTIVO' => true],
            ['ID_TIPODOCUMENTO' => 4, 'CODIGO_MH' => '02', 'NOMBREDOCUMENTO' => 'Carnet de Residente', 'MASCARA_FORMATO' => null, 'ESACTIVO' => true],
            ['ID_TIPODOCUMENTO' => 5, 'CODIGO_MH' => '37', 'NOMBREDOCUMENTO' => 'Otro Documento de Identificación', 'MASCARA_FORMATO' => null, 'ESACTIVO' => true]
        ];

        foreach ($documentos as $doc) {
            DB::table('TIPO_DOCUMENTO_IDENTIDAD')->updateOrInsert(['ID_TIPODOCUMENTO' => $doc['ID_TIPODOCUMENTO']], $doc);
        }

        // 2. Actividades Económicas CIIU (CAT-019 MH)
        $actividades = [
            ['ID_ACTIVIDAD_ECONOMICA' => 1, 'CODIGO_MH' => '01111', 'DESCRIPCION' => 'Cultivo de cereales excepto arroz y para forrajes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 2, 'CODIGO_MH' => '01112', 'DESCRIPCION' => 'Cultivo de legumbres', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 3, 'CODIGO_MH' => '01113', 'DESCRIPCION' => 'Cultivo de semillas oleaginosas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 4, 'CODIGO_MH' => '01114', 'DESCRIPCION' => 'Cultivo de plantas para la preparación de semillas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 5, 'CODIGO_MH' => '01119', 'DESCRIPCION' => 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 6, 'CODIGO_MH' => '01120', 'DESCRIPCION' => 'Cultivo de arroz', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 7, 'CODIGO_MH' => '01131', 'DESCRIPCION' => 'Cultivo de raíces y tubérculos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 8, 'CODIGO_MH' => '01132', 'DESCRIPCION' => 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 9, 'CODIGO_MH' => '01133', 'DESCRIPCION' => 'Cultivo hortícola de fruto', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 10, 'CODIGO_MH' => '01134', 'DESCRIPCION' => 'Cultivo de hortalizas de hoja y otras hortalizas ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 11, 'CODIGO_MH' => '01140', 'DESCRIPCION' => 'Cultivo de caña de azúcar', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 12, 'CODIGO_MH' => '01150', 'DESCRIPCION' => 'Cultivo de tabaco', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 13, 'CODIGO_MH' => '01161', 'DESCRIPCION' => 'Cultivo de algodón', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 14, 'CODIGO_MH' => '01162', 'DESCRIPCION' => 'Cultivo de fibras vegetales excepto algodón', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 15, 'CODIGO_MH' => '01191', 'DESCRIPCION' => 'Cultivo de plantas no perennes para la producción de semillas y flores', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 16, 'CODIGO_MH' => '01192', 'DESCRIPCION' => 'Cultivo de cereales y pastos para la alimentación animal', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 17, 'CODIGO_MH' => '01199', 'DESCRIPCION' => 'Producción de cultivos no estacionales ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 18, 'CODIGO_MH' => '01220', 'DESCRIPCION' => 'Cultivo de frutas tropicales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 19, 'CODIGO_MH' => '01230', 'DESCRIPCION' => 'Cultivo de cítricos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 20, 'CODIGO_MH' => '01240', 'DESCRIPCION' => 'Cultivo de frutas de pepita y hueso', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 21, 'CODIGO_MH' => '01251', 'DESCRIPCION' => 'Cultivo de frutas ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 22, 'CODIGO_MH' => '01252', 'DESCRIPCION' => 'Cultivo de otros frutos y nueces de árboles y arbustos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 23, 'CODIGO_MH' => '01260', 'DESCRIPCION' => 'Cultivo de frutos oleaginosos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 24, 'CODIGO_MH' => '01271', 'DESCRIPCION' => 'Cultivo de café', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 25, 'CODIGO_MH' => '01272', 'DESCRIPCION' => 'Cultivo de plantas para la elaboración de bebidas excepto café', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 26, 'CODIGO_MH' => '01281', 'DESCRIPCION' => 'Cultivo de especias y aromáticas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 27, 'CODIGO_MH' => '01282', 'DESCRIPCION' => 'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 28, 'CODIGO_MH' => '01291', 'DESCRIPCION' => 'Cultivo de árboles de hule (caucho) para la obtención de látex', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 29, 'CODIGO_MH' => '01292', 'DESCRIPCION' => 'Cultivo de plantas para la obtención de productos químicos y colorantes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 30, 'CODIGO_MH' => '01299', 'DESCRIPCION' => 'Producción de cultivos perennes ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 31, 'CODIGO_MH' => '01300', 'DESCRIPCION' => 'Propagación de plantas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 32, 'CODIGO_MH' => '01301', 'DESCRIPCION' => 'Cultivo de plantas y flores ornamentales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 33, 'CODIGO_MH' => '01410', 'DESCRIPCION' => 'Cría y engorde de ganado bovino', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 34, 'CODIGO_MH' => '01420', 'DESCRIPCION' => 'Cría de caballos y otros equinos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 35, 'CODIGO_MH' => '01440', 'DESCRIPCION' => 'Cría de ovejas y cabras', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 36, 'CODIGO_MH' => '01450', 'DESCRIPCION' => 'Cría de cerdos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 37, 'CODIGO_MH' => '01460', 'DESCRIPCION' => 'Cría de aves de corral y producción de huevos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 38, 'CODIGO_MH' => '01491', 'DESCRIPCION' => 'Cría de abejas apicultura para la obtención de miel y otros productos apícolas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 39, 'CODIGO_MH' => '01492', 'DESCRIPCION' => 'Cría de conejos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 40, 'CODIGO_MH' => '01493', 'DESCRIPCION' => 'Cría de iguanas y garrobos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 41, 'CODIGO_MH' => '01494', 'DESCRIPCION' => 'Cría de mariposas y otros insectos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 42, 'CODIGO_MH' => '01499', 'DESCRIPCION' => 'Cría y obtención de productos animales n.c', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 43, 'CODIGO_MH' => '01500', 'DESCRIPCION' => 'Cultivo de productos agrícolas en combinación con la cría de animales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 44, 'CODIGO_MH' => '01611', 'DESCRIPCION' => 'Servicios de maquinaria agrícola', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 45, 'CODIGO_MH' => '01612', 'DESCRIPCION' => 'Control de plagas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 46, 'CODIGO_MH' => '01613', 'DESCRIPCION' => 'Servicios de riego', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 47, 'CODIGO_MH' => '01614', 'DESCRIPCION' => 'Servicios de contratación de mano de obra para la agricultura', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 48, 'CODIGO_MH' => '01619', 'DESCRIPCION' => 'Servicios agrícolas ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 49, 'CODIGO_MH' => '01621', 'DESCRIPCION' => 'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 50, 'CODIGO_MH' => '01622', 'DESCRIPCION' => 'Servicios de mano de obra pecuaria', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 51, 'CODIGO_MH' => '01629', 'DESCRIPCION' => 'Servicios pecuarios ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 52, 'CODIGO_MH' => '01631', 'DESCRIPCION' => 'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 53, 'CODIGO_MH' => '01632', 'DESCRIPCION' => 'Servicio de beneficio de café', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 54, 'CODIGO_MH' => '01633', 'DESCRIPCION' => 'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 55, 'CODIGO_MH' => '01640', 'DESCRIPCION' => 'Tratamiento de semillas para la propagación', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 56, 'CODIGO_MH' => '01700', 'DESCRIPCION' => 'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 57, 'CODIGO_MH' => '02100', 'DESCRIPCION' => 'Silvicultura y otras actividades forestales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 58, 'CODIGO_MH' => '02200', 'DESCRIPCION' => 'Extracción de madera', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 59, 'CODIGO_MH' => '02300', 'DESCRIPCION' => 'Recolección de productos diferentes a la madera', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 60, 'CODIGO_MH' => '02400', 'DESCRIPCION' => 'Servicios de apoyo a la silvicultura', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 61, 'CODIGO_MH' => '03110', 'DESCRIPCION' => 'Pesca marítima de altura y costera', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 62, 'CODIGO_MH' => '03120', 'DESCRIPCION' => 'Pesca de agua dulce', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 63, 'CODIGO_MH' => '03210', 'DESCRIPCION' => 'Acuicultura marítima', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 64, 'CODIGO_MH' => '03220', 'DESCRIPCION' => 'Acuicultura de agua dulce', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 65, 'CODIGO_MH' => '03300', 'DESCRIPCION' => 'Servicios de apoyo a la pesca y acuicultura', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 66, 'CODIGO_MH' => '05100', 'DESCRIPCION' => 'Extracción de hulla', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 67, 'CODIGO_MH' => '05200', 'DESCRIPCION' => 'Extracción y aglomeración de lignito', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 68, 'CODIGO_MH' => '06100', 'DESCRIPCION' => 'Extracción de petróleo crudo', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 69, 'CODIGO_MH' => '06200', 'DESCRIPCION' => 'Extracción de gas natural', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 70, 'CODIGO_MH' => '07100', 'DESCRIPCION' => 'Extracción de minerales de hierro', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 71, 'CODIGO_MH' => '07210', 'DESCRIPCION' => 'Extracción de minerales de uranio y torio', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 72, 'CODIGO_MH' => '07290', 'DESCRIPCION' => 'Extracción de minerales metalíferos no ferrosos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 73, 'CODIGO_MH' => '08100', 'DESCRIPCION' => 'Extracción de piedra, arena y arcilla', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 74, 'CODIGO_MH' => '08910', 'DESCRIPCION' => 'Extracción de minerales para la fabricación de abonos y productos químicos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 75, 'CODIGO_MH' => '08920', 'DESCRIPCION' => 'Extracción y aglomeración de turba', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 76, 'CODIGO_MH' => '08930', 'DESCRIPCION' => 'Extracción de sal', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 77, 'CODIGO_MH' => '08990', 'DESCRIPCION' => 'Explotación de otras minas y canteras ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 78, 'CODIGO_MH' => '09100', 'DESCRIPCION' => 'Actividades de apoyo a la extracción de petróleo y gas natural', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 79, 'CODIGO_MH' => '09900', 'DESCRIPCION' => 'Actividades de apoyo a la explotación de minas y canteras', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 80, 'CODIGO_MH' => '10101', 'DESCRIPCION' => 'Servicio de rastros y mataderos de bovinos y porcinos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 81, 'CODIGO_MH' => '10102', 'DESCRIPCION' => 'Matanza y procesamiento de bovinos y porcinos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 82, 'CODIGO_MH' => '10103', 'DESCRIPCION' => 'Matanza y procesamientos de aves de corral', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 83, 'CODIGO_MH' => '10104', 'DESCRIPCION' => 'Elaboración y conservación de embutidos y tripas naturales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 84, 'CODIGO_MH' => '10105', 'DESCRIPCION' => 'Servicios de conservación y empaque de carnes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 85, 'CODIGO_MH' => '10106', 'DESCRIPCION' => 'Elaboración y conservación de grasas y aceites animales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 86, 'CODIGO_MH' => '10107', 'DESCRIPCION' => 'Servicios de molienda de carne', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 87, 'CODIGO_MH' => '10108', 'DESCRIPCION' => 'Elaboración de productos de carne ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 88, 'CODIGO_MH' => '10201', 'DESCRIPCION' => 'Procesamiento y conservación de pescado, crustáceos y moluscos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 89, 'CODIGO_MH' => '10209', 'DESCRIPCION' => 'Fabricación de productos de pescado ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 90, 'CODIGO_MH' => '10301', 'DESCRIPCION' => 'Elaboración de jugos de frutas y hortalizas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 91, 'CODIGO_MH' => '10302', 'DESCRIPCION' => 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 92, 'CODIGO_MH' => '10309', 'DESCRIPCION' => 'Elaboración de productos de frutas y hortalizas n.c.p.', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 93, 'CODIGO_MH' => '10401', 'DESCRIPCION' => 'Fabricación de aceites y grasas vegetales y animales comestibles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 94, 'CODIGO_MH' => '10402', 'DESCRIPCION' => 'Fabricación de aceites y grasas vegetales y animales no comestibles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 95, 'CODIGO_MH' => '10409', 'DESCRIPCION' => 'Servicio de maquilado de aceites', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 96, 'CODIGO_MH' => '10501', 'DESCRIPCION' => 'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 97, 'CODIGO_MH' => '10502', 'DESCRIPCION' => 'Fabricación de sorbetes y helados', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 98, 'CODIGO_MH' => '10503', 'DESCRIPCION' => 'Fabricación de quesos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 99, 'CODIGO_MH' => '10611', 'DESCRIPCION' => 'Molienda de cereales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 100, 'CODIGO_MH' => '10612', 'DESCRIPCION' => 'Elaboración de cereales para el desayuno y similares', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 101, 'CODIGO_MH' => '10613', 'DESCRIPCION' => 'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163)', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 102, 'CODIGO_MH' => '10621', 'DESCRIPCION' => 'Fabricación de almidón', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 103, 'CODIGO_MH' => '10628', 'DESCRIPCION' => 'Servicio de molienda de maíz húmedo molino para nixtamal', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 104, 'CODIGO_MH' => '10711', 'DESCRIPCION' => 'Elaboración de tortillas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 105, 'CODIGO_MH' => '10712', 'DESCRIPCION' => 'Fabricación de pan, galletas y barquillos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 106, 'CODIGO_MH' => '10713', 'DESCRIPCION' => 'Fabricación de repostería', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 107, 'CODIGO_MH' => '10721', 'DESCRIPCION' => 'Ingenios azucareros', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 108, 'CODIGO_MH' => '10722', 'DESCRIPCION' => 'Molienda de caña de azúcar para la elaboración de dulces', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 109, 'CODIGO_MH' => '10723', 'DESCRIPCION' => 'Elaboración de jarabes de azúcar y otros similares', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 110, 'CODIGO_MH' => '10724', 'DESCRIPCION' => 'Maquilado de azúcar de caña', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 111, 'CODIGO_MH' => '10730', 'DESCRIPCION' => 'Fabricación de cacao, chocolates y productos de confitería', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 112, 'CODIGO_MH' => '10740', 'DESCRIPCION' => 'Elaboración de macarrones, fideos, y productos farináceos similares', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 113, 'CODIGO_MH' => '10750', 'DESCRIPCION' => 'Elaboración de comidas y platos preparados para la reventa en locales y/o para exportación', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 114, 'CODIGO_MH' => '10791', 'DESCRIPCION' => 'Elaboración de productos de café', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 115, 'CODIGO_MH' => '10792', 'DESCRIPCION' => 'Elaboración de especies, sazonadores y condimentos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 116, 'CODIGO_MH' => '10793', 'DESCRIPCION' => 'Elaboración de sopas, cremas y consomé', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 117, 'CODIGO_MH' => '10794', 'DESCRIPCION' => 'Fabricación de bocadillos tostados y/o fritos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 118, 'CODIGO_MH' => '10799', 'DESCRIPCION' => 'Elaboración de productos alimenticios ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 119, 'CODIGO_MH' => '10800', 'DESCRIPCION' => 'Elaboración de alimentos preparados para animales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 120, 'CODIGO_MH' => '11012', 'DESCRIPCION' => 'Fabricación de aguardiente y licores', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 121, 'CODIGO_MH' => '11020', 'DESCRIPCION' => 'Elaboración de vinos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 122, 'CODIGO_MH' => '11030', 'DESCRIPCION' => 'Fabricación de cerveza', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 123, 'CODIGO_MH' => '11041', 'DESCRIPCION' => 'Fabricación de aguas gaseosas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 124, 'CODIGO_MH' => '11042', 'DESCRIPCION' => 'Fabricación y envasado de agua', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 125, 'CODIGO_MH' => '11043', 'DESCRIPCION' => 'Elaboración de refrescos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 126, 'CODIGO_MH' => '11048', 'DESCRIPCION' => 'Maquilado de aguas gaseosas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 127, 'CODIGO_MH' => '11049', 'DESCRIPCION' => 'Elaboración de bebidas no alcohólicas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 128, 'CODIGO_MH' => '12000', 'DESCRIPCION' => 'Elaboración de productos de tabaco', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 129, 'CODIGO_MH' => '13111', 'DESCRIPCION' => 'Preparación de fibras textiles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 130, 'CODIGO_MH' => '13112', 'DESCRIPCION' => 'Fabricación de hilados', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 131, 'CODIGO_MH' => '13120', 'DESCRIPCION' => 'Fabricación de telas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 132, 'CODIGO_MH' => '13130', 'DESCRIPCION' => 'Acabado de productos textiles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 133, 'CODIGO_MH' => '13910', 'DESCRIPCION' => 'Fabricación de tejidos de punto y ganchillo', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 134, 'CODIGO_MH' => '13921', 'DESCRIPCION' => 'Fabricación de productos textiles para el hogar', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 135, 'CODIGO_MH' => '13922', 'DESCRIPCION' => 'Sacos, bolsas y otros artículos textiles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 136, 'CODIGO_MH' => '13929', 'DESCRIPCION' => 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir n.c.p', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 137, 'CODIGO_MH' => '13930', 'DESCRIPCION' => 'Fabricación de tapices y alfombras', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 138, 'CODIGO_MH' => '13941', 'DESCRIPCION' => 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 139, 'CODIGO_MH' => '13942', 'DESCRIPCION' => 'Fabricación de redes de diversos materiales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 140, 'CODIGO_MH' => '13948', 'DESCRIPCION' => 'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 141, 'CODIGO_MH' => '13991', 'DESCRIPCION' => 'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 142, 'CODIGO_MH' => '13992', 'DESCRIPCION' => 'Servicio de bordados en artículos y prendas de tela', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 143, 'CODIGO_MH' => '13999', 'DESCRIPCION' => 'Fabricación de productos textiles ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 144, 'CODIGO_MH' => '14101', 'DESCRIPCION' => 'Fabricación de ropa interior, para dormir y similares', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 145, 'CODIGO_MH' => '14102', 'DESCRIPCION' => 'Fabricación de ropa para niños', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 146, 'CODIGO_MH' => '14103', 'DESCRIPCION' => 'Fabricación de prendas de vestir para ambos sexos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 147, 'CODIGO_MH' => '14104', 'DESCRIPCION' => 'Confección de prendas a medida', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 148, 'CODIGO_MH' => '14105', 'DESCRIPCION' => 'Fabricación de prendas de vestir para deportes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 149, 'CODIGO_MH' => '14106', 'DESCRIPCION' => 'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 150, 'CODIGO_MH' => '14108', 'DESCRIPCION' => 'Maquilado de prendas de vestir, accesorios y otros', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 151, 'CODIGO_MH' => '14109', 'DESCRIPCION' => 'Fabricación de prendas y accesorios de vestir n.c.p.', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 152, 'CODIGO_MH' => '14200', 'DESCRIPCION' => 'Fabricación de artículos de piel', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 153, 'CODIGO_MH' => '14301', 'DESCRIPCION' => 'Fabricación de calcetines, calcetas, medias (panty house) y otros similares', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 154, 'CODIGO_MH' => '14302', 'DESCRIPCION' => 'Fabricación de ropa interior de tejido de punto', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 155, 'CODIGO_MH' => '14309', 'DESCRIPCION' => 'Fabricación de prendas de vestir de tejido de punto ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 156, 'CODIGO_MH' => '15110', 'DESCRIPCION' => 'Curtido y adobo de cueros; adobo y teñido de pieles', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 157, 'CODIGO_MH' => '15121', 'DESCRIPCION' => 'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 158, 'CODIGO_MH' => '15122', 'DESCRIPCION' => 'Fabricación de monturas, accesorios y vainas talabartería', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 159, 'CODIGO_MH' => '15123', 'DESCRIPCION' => 'Fabricación de artesanías principalmente de cuero natural y sintético', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 160, 'CODIGO_MH' => '15128', 'DESCRIPCION' => 'Maquilado de artículos de cuero natural, sintético y de otros materiales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 161, 'CODIGO_MH' => '15201', 'DESCRIPCION' => 'Fabricación de calzado', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 162, 'CODIGO_MH' => '15202', 'DESCRIPCION' => 'Fabricación de partes y accesorios de calzado', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 163, 'CODIGO_MH' => '15208', 'DESCRIPCION' => 'Maquilado de partes y accesorios de calzado', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 164, 'CODIGO_MH' => '16100', 'DESCRIPCION' => 'Aserradero y acepilladura de madera', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 165, 'CODIGO_MH' => '16210', 'DESCRIPCION' => 'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 166, 'CODIGO_MH' => '16220', 'DESCRIPCION' => 'Fabricación de partes y piezas de carpintería para edificios y construcciones', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 167, 'CODIGO_MH' => '16230', 'DESCRIPCION' => 'Fabricación de envases y recipientes de madera', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 168, 'CODIGO_MH' => '16292', 'DESCRIPCION' => 'Fabricación de artesanías de madera, semillas, materiales trenzables', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 169, 'CODIGO_MH' => '16299', 'DESCRIPCION' => 'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 170, 'CODIGO_MH' => '17010', 'DESCRIPCION' => 'Fabricación de pasta de madera, papel y cartón', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 171, 'CODIGO_MH' => '17020', 'DESCRIPCION' => 'Fabricación de papel y cartón ondulado y envases de papel y cartón', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 172, 'CODIGO_MH' => '17091', 'DESCRIPCION' => 'Fabricación de artículos de papel y cartón de uso personal y doméstico', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 173, 'CODIGO_MH' => '17092', 'DESCRIPCION' => 'Fabricación de productos de papel ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 174, 'CODIGO_MH' => '18110', 'DESCRIPCION' => 'Impresión', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 175, 'CODIGO_MH' => '18120', 'DESCRIPCION' => 'Servicios relacionados con la impresión', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 176, 'CODIGO_MH' => '18200', 'DESCRIPCION' => 'Reproducción de grabaciones', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 177, 'CODIGO_MH' => '19100', 'DESCRIPCION' => 'Fabricación de productos de hornos de coque', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 178, 'CODIGO_MH' => '19201', 'DESCRIPCION' => 'Fabricación de combustible', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 179, 'CODIGO_MH' => '19202', 'DESCRIPCION' => 'Fabricación de aceites y lubricantes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 180, 'CODIGO_MH' => '20111', 'DESCRIPCION' => 'Fabricación de materias primas para la fabricación de colorantes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 181, 'CODIGO_MH' => '20112', 'DESCRIPCION' => 'Fabricación de materiales curtientes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 182, 'CODIGO_MH' => '20113', 'DESCRIPCION' => 'Fabricación de gases industriales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 183, 'CODIGO_MH' => '20114', 'DESCRIPCION' => 'Fabricación de alcohol etílico', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 184, 'CODIGO_MH' => '20119', 'DESCRIPCION' => 'Fabricación de sustancias químicas básicas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 185, 'CODIGO_MH' => '20120', 'DESCRIPCION' => 'Fabricación de abonos y fertilizantes', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 186, 'CODIGO_MH' => '20130', 'DESCRIPCION' => 'Fabricación de plástico y caucho en formas primarias', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 187, 'CODIGO_MH' => '20210', 'DESCRIPCION' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 188, 'CODIGO_MH' => '20220', 'DESCRIPCION' => 'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 189, 'CODIGO_MH' => '20231', 'DESCRIPCION' => 'Fabricación de jabones, detergentes y similares para limpieza', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 190, 'CODIGO_MH' => '20232', 'DESCRIPCION' => 'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 191, 'CODIGO_MH' => '20291', 'DESCRIPCION' => 'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 192, 'CODIGO_MH' => '20292', 'DESCRIPCION' => 'Fabricación de productos pirotécnicos, explosivos y municiones', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 193, 'CODIGO_MH' => '20299', 'DESCRIPCION' => 'Fabricación de productos químicos n.c.p.', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 194, 'CODIGO_MH' => '20300', 'DESCRIPCION' => 'Fabricación de fibras artificiales', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 195, 'CODIGO_MH' => '21001', 'DESCRIPCION' => 'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 196, 'CODIGO_MH' => '21008', 'DESCRIPCION' => 'Maquilado de medicamentos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 197, 'CODIGO_MH' => '22110', 'DESCRIPCION' => 'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 198, 'CODIGO_MH' => '22190', 'DESCRIPCION' => 'Fabricación de otros productos de caucho', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 199, 'CODIGO_MH' => '22201', 'DESCRIPCION' => 'Fabricación de envases plásticos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 200, 'CODIGO_MH' => '22202', 'DESCRIPCION' => 'Fabricación de productos plásticos para uso personal o doméstico', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 201, 'CODIGO_MH' => '22208', 'DESCRIPCION' => 'Maquila de plásticos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 202, 'CODIGO_MH' => '22209', 'DESCRIPCION' => 'Fabricación de productos plásticos n.c.p.', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 203, 'CODIGO_MH' => '23101', 'DESCRIPCION' => 'Fabricación de vidrio', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 204, 'CODIGO_MH' => '23102', 'DESCRIPCION' => 'Fabricación de recipientes y envases de vidrio', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 205, 'CODIGO_MH' => '23108', 'DESCRIPCION' => 'Servicio de maquilado', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 206, 'CODIGO_MH' => '23109', 'DESCRIPCION' => 'Fabricación de productos de vidrio ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 207, 'CODIGO_MH' => '23910', 'DESCRIPCION' => 'Fabricación de productos refractarios', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 208, 'CODIGO_MH' => '23920', 'DESCRIPCION' => 'Fabricación de productos de arcilla para la construcción', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 209, 'CODIGO_MH' => '23931', 'DESCRIPCION' => 'Fabricación de productos de cerámica y porcelana no refractaria', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 210, 'CODIGO_MH' => '23932', 'DESCRIPCION' => 'Fabricación de productos de cerámica y porcelana ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 211, 'CODIGO_MH' => '23940', 'DESCRIPCION' => 'Fabricación de cemento, cal y yeso', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 212, 'CODIGO_MH' => '23950', 'DESCRIPCION' => 'Fabricación de artículos de hormigón, cemento y yeso', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 213, 'CODIGO_MH' => '23960', 'DESCRIPCION' => 'Corte, tallado y acabado de la piedra', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 214, 'CODIGO_MH' => '23990', 'DESCRIPCION' => 'Fabricación de productos minerales no metálicos ncp', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 215, 'CODIGO_MH' => '24100', 'DESCRIPCION' => 'Industrias básicas de hierro y acero', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 216, 'CODIGO_MH' => '24200', 'DESCRIPCION' => 'Fabricación de productos primarios de metales preciosos y metales no ferrosos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 217, 'CODIGO_MH' => '24310', 'DESCRIPCION' => 'Fundición de hierro y acero', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 218, 'CODIGO_MH' => '24320', 'DESCRIPCION' => 'Fundición de metales no ferrosos', 'ESACTIVO' => true],
            ['ID_ACTIVIDAD_ECONOMICA' => 219, 'CODIGO_MH' => '25111', 'DESCRIPCION' => 'Fabricación de productos metálicos para uso estructura', 'ESACTIVO' => true]
        ];

        foreach ($actividades as $act) {
            DB::table('ACTIVIDAD_ECONOMICA')->updateOrInsert(['ID_ACTIVIDAD_ECONOMICA' => $act['ID_ACTIVIDAD_ECONOMICA']], $act);
        }
    }
}
