<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        $paises = [
            ['ID_PAIS' => 1, 'CODIGO_MH' => 'AF', 'NOMBREPAIS' => 'Afganistán'],
            ['ID_PAIS' => 2, 'CODIGO_MH' => 'AX', 'NOMBREPAIS' => 'Aland'],
            ['ID_PAIS' => 3, 'CODIGO_MH' => 'AL', 'NOMBREPAIS' => 'Albania'],
            ['ID_PAIS' => 4, 'CODIGO_MH' => 'DE', 'NOMBREPAIS' => 'Alemania'],
            ['ID_PAIS' => 5, 'CODIGO_MH' => 'AD', 'NOMBREPAIS' => 'Andorra'],
            ['ID_PAIS' => 6, 'CODIGO_MH' => 'AO', 'NOMBREPAIS' => 'Angola'],
            ['ID_PAIS' => 7, 'CODIGO_MH' => 'AI', 'NOMBREPAIS' => 'Anguila'],
            ['ID_PAIS' => 8, 'CODIGO_MH' => 'AQ', 'NOMBREPAIS' => 'Antártica'],
            ['ID_PAIS' => 9, 'CODIGO_MH' => 'AG', 'NOMBREPAIS' => 'Antigua y Barbuda'],
            ['ID_PAIS' => 10, 'CODIGO_MH' => 'AW', 'NOMBREPAIS' => 'Aruba'],
            ['ID_PAIS' => 11, 'CODIGO_MH' => 'SA', 'NOMBREPAIS' => 'Arabia Saudita'],
            ['ID_PAIS' => 12, 'CODIGO_MH' => 'DZ', 'NOMBREPAIS' => 'Argelia'],
            ['ID_PAIS' => 13, 'CODIGO_MH' => 'AR', 'NOMBREPAIS' => 'Argentina'],
            ['ID_PAIS' => 14, 'CODIGO_MH' => 'AM', 'NOMBREPAIS' => 'Armenia'],
            ['ID_PAIS' => 15, 'CODIGO_MH' => 'AU', 'NOMBREPAIS' => 'Australia'],
            ['ID_PAIS' => 16, 'CODIGO_MH' => 'AT', 'NOMBREPAIS' => 'Austria'],
            ['ID_PAIS' => 17, 'CODIGO_MH' => 'AZ', 'NOMBREPAIS' => 'Azerbaiyán'],
            ['ID_PAIS' => 18, 'CODIGO_MH' => 'BS', 'NOMBREPAIS' => 'Bahamas'],
            ['ID_PAIS' => 19, 'CODIGO_MH' => 'BH', 'NOMBREPAIS' => 'Bahrein'],
            ['ID_PAIS' => 20, 'CODIGO_MH' => 'BD', 'NOMBREPAIS' => 'Bangladesh'],
            ['ID_PAIS' => 21, 'CODIGO_MH' => 'BB', 'NOMBREPAIS' => 'Barbados'],
            ['ID_PAIS' => 22, 'CODIGO_MH' => 'BE', 'NOMBREPAIS' => 'Bélgica'],
            ['ID_PAIS' => 23, 'CODIGO_MH' => 'BZ', 'NOMBREPAIS' => 'Belice'],
            ['ID_PAIS' => 24, 'CODIGO_MH' => 'BJ', 'NOMBREPAIS' => 'Benin'],
            ['ID_PAIS' => 25, 'CODIGO_MH' => 'BM', 'NOMBREPAIS' => 'Bermudas'],
            ['ID_PAIS' => 26, 'CODIGO_MH' => 'BY', 'NOMBREPAIS' => 'Bielorrusia'],
            ['ID_PAIS' => 27, 'CODIGO_MH' => 'BO', 'NOMBREPAIS' => 'Bolivia'],
            ['ID_PAIS' => 28, 'CODIGO_MH' => 'BQ', 'NOMBREPAIS' => 'Bonaire, Sint Eustatius and Saba'],
            ['ID_PAIS' => 29, 'CODIGO_MH' => 'BA', 'NOMBREPAIS' => 'Bosnia-Herzegovina'],
            ['ID_PAIS' => 30, 'CODIGO_MH' => 'BW', 'NOMBREPAIS' => 'Botswana'],
            ['ID_PAIS' => 31, 'CODIGO_MH' => 'BR', 'NOMBREPAIS' => 'Brasil'],
            ['ID_PAIS' => 32, 'CODIGO_MH' => 'BN', 'NOMBREPAIS' => 'Brunei'],
            ['ID_PAIS' => 33, 'CODIGO_MH' => 'BG', 'NOMBREPAIS' => 'Bulgaria'],
            ['ID_PAIS' => 34, 'CODIGO_MH' => 'BF', 'NOMBREPAIS' => 'Burkina Faso'],
            ['ID_PAIS' => 35, 'CODIGO_MH' => 'BI', 'NOMBREPAIS' => 'Burundi'],
            ['ID_PAIS' => 36, 'CODIGO_MH' => 'BT', 'NOMBREPAIS' => 'Bután'],
            ['ID_PAIS' => 37, 'CODIGO_MH' => 'CV', 'NOMBREPAIS' => 'Cabo Verde'],
            ['ID_PAIS' => 38, 'CODIGO_MH' => 'KY', 'NOMBREPAIS' => 'Caimán, Islas'],
            ['ID_PAIS' => 39, 'CODIGO_MH' => 'KH', 'NOMBREPAIS' => 'Camboya'],
            ['ID_PAIS' => 40, 'CODIGO_MH' => 'CM', 'NOMBREPAIS' => 'Camerún'],
            ['ID_PAIS' => 41, 'CODIGO_MH' => 'CA', 'NOMBREPAIS' => 'Canadá'],
            ['ID_PAIS' => 42, 'CODIGO_MH' => 'CF', 'NOMBREPAIS' => 'Centroafricana, República'],
            ['ID_PAIS' => 43, 'CODIGO_MH' => 'TD', 'NOMBREPAIS' => 'Chad'],
            ['ID_PAIS' => 44, 'CODIGO_MH' => 'CL', 'NOMBREPAIS' => 'Chile'],
            ['ID_PAIS' => 45, 'CODIGO_MH' => 'CN', 'NOMBREPAIS' => 'China'],
            ['ID_PAIS' => 46, 'CODIGO_MH' => 'CY', 'NOMBREPAIS' => 'Chipre'],
            ['ID_PAIS' => 47, 'CODIGO_MH' => 'VA', 'NOMBREPAIS' => 'Ciudad del Vaticano'],
            ['ID_PAIS' => 48, 'CODIGO_MH' => 'CO', 'NOMBREPAIS' => 'Colombia'],
            ['ID_PAIS' => 49, 'CODIGO_MH' => 'KM', 'NOMBREPAIS' => 'Comoras'],
            ['ID_PAIS' => 50, 'CODIGO_MH' => 'CG', 'NOMBREPAIS' => 'Congo'],
            ['ID_PAIS' => 51, 'CODIGO_MH' => 'CI', 'NOMBREPAIS' => 'Costa de Marfil'],
            ['ID_PAIS' => 52, 'CODIGO_MH' => 'CR', 'NOMBREPAIS' => 'Costa Rica'],
            ['ID_PAIS' => 53, 'CODIGO_MH' => 'HR', 'NOMBREPAIS' => 'Croacia'],
            ['ID_PAIS' => 54, 'CODIGO_MH' => 'CU', 'NOMBREPAIS' => 'Cuba'],
            ['ID_PAIS' => 55, 'CODIGO_MH' => 'CW', 'NOMBREPAIS' => 'Curazao'],
            ['ID_PAIS' => 56, 'CODIGO_MH' => 'DK', 'NOMBREPAIS' => 'Dinamarca'],
            ['ID_PAIS' => 57, 'CODIGO_MH' => 'DM', 'NOMBREPAIS' => 'Dominica'],
            ['ID_PAIS' => 58, 'CODIGO_MH' => 'DJ', 'NOMBREPAIS' => 'Djiboutí'],
            ['ID_PAIS' => 59, 'CODIGO_MH' => 'EC', 'NOMBREPAIS' => 'Ecuador'],
            ['ID_PAIS' => 60, 'CODIGO_MH' => 'EG', 'NOMBREPAIS' => 'Egipto'],
            ['ID_PAIS' => 61, 'CODIGO_MH' => 'SV', 'NOMBREPAIS' => 'El Salvador'],
            ['ID_PAIS' => 62, 'CODIGO_MH' => 'AE', 'NOMBREPAIS' => 'Emiratos Árabes Unidos'],
            ['ID_PAIS' => 63, 'CODIGO_MH' => 'ER', 'NOMBREPAIS' => 'Eritrea'],
            ['ID_PAIS' => 64, 'CODIGO_MH' => 'SK', 'NOMBREPAIS' => 'Eslovaquia'],
            ['ID_PAIS' => 65, 'CODIGO_MH' => 'SI', 'NOMBREPAIS' => 'Eslovenia'],
            ['ID_PAIS' => 66, 'CODIGO_MH' => 'ES', 'NOMBREPAIS' => 'España'],
            ['ID_PAIS' => 67, 'CODIGO_MH' => 'US', 'NOMBREPAIS' => 'Estados Unidos'],
            ['ID_PAIS' => 68, 'CODIGO_MH' => 'EE', 'NOMBREPAIS' => 'Estonia'],
            ['ID_PAIS' => 69, 'CODIGO_MH' => 'ET', 'NOMBREPAIS' => 'Etiopía'],
            ['ID_PAIS' => 70, 'CODIGO_MH' => 'FJ', 'NOMBREPAIS' => 'Fiji'],
            ['ID_PAIS' => 71, 'CODIGO_MH' => 'PH', 'NOMBREPAIS' => 'Filipinas'],
            ['ID_PAIS' => 72, 'CODIGO_MH' => 'FI', 'NOMBREPAIS' => 'Finlandia'],
            ['ID_PAIS' => 73, 'CODIGO_MH' => 'FR', 'NOMBREPAIS' => 'Francia'],
            ['ID_PAIS' => 74, 'CODIGO_MH' => 'GA', 'NOMBREPAIS' => 'Gabón'],
            ['ID_PAIS' => 75, 'CODIGO_MH' => 'GM', 'NOMBREPAIS' => 'Gambia'],
            ['ID_PAIS' => 76, 'CODIGO_MH' => 'GE', 'NOMBREPAIS' => 'Georgia'],
            ['ID_PAIS' => 77, 'CODIGO_MH' => 'GH', 'NOMBREPAIS' => 'Ghana'],
            ['ID_PAIS' => 78, 'CODIGO_MH' => 'GI', 'NOMBREPAIS' => 'Gibraltar'],
            ['ID_PAIS' => 79, 'CODIGO_MH' => 'GD', 'NOMBREPAIS' => 'Granada'],
            ['ID_PAIS' => 80, 'CODIGO_MH' => 'GR', 'NOMBREPAIS' => 'Grecia'],
            ['ID_PAIS' => 81, 'CODIGO_MH' => 'GL', 'NOMBREPAIS' => 'Groenlandia'],
            ['ID_PAIS' => 82, 'CODIGO_MH' => 'GP', 'NOMBREPAIS' => 'Guadalupe'],
            ['ID_PAIS' => 83, 'CODIGO_MH' => 'GU', 'NOMBREPAIS' => 'Guam'],
            ['ID_PAIS' => 84, 'CODIGO_MH' => 'GT', 'NOMBREPAIS' => 'Guatemala'],
            ['ID_PAIS' => 85, 'CODIGO_MH' => 'GF', 'NOMBREPAIS' => 'Guayana Francesa'],
            ['ID_PAIS' => 86, 'CODIGO_MH' => 'GG', 'NOMBREPAIS' => 'Guernsey'],
            ['ID_PAIS' => 87, 'CODIGO_MH' => 'GN', 'NOMBREPAIS' => 'Guinea'],
            ['ID_PAIS' => 88, 'CODIGO_MH' => 'GQ', 'NOMBREPAIS' => 'Guinea Ecuatorial'],
            ['ID_PAIS' => 89, 'CODIGO_MH' => 'GW', 'NOMBREPAIS' => 'Guinea-Bissau'],
            ['ID_PAIS' => 90, 'CODIGO_MH' => 'GY', 'NOMBREPAIS' => 'Guyana'],
            ['ID_PAIS' => 91, 'CODIGO_MH' => 'HT', 'NOMBREPAIS' => 'Haití'],
            ['ID_PAIS' => 92, 'CODIGO_MH' => 'HN', 'NOMBREPAIS' => 'Honduras'],
            ['ID_PAIS' => 93, 'CODIGO_MH' => 'HK', 'NOMBREPAIS' => 'Hong Kong'],
            ['ID_PAIS' => 94, 'CODIGO_MH' => 'HU', 'NOMBREPAIS' => 'Hungría'],
            ['ID_PAIS' => 95, 'CODIGO_MH' => 'IN', 'NOMBREPAIS' => 'India'],
            ['ID_PAIS' => 96, 'CODIGO_MH' => 'ID', 'NOMBREPAIS' => 'Indonesia'],
            ['ID_PAIS' => 97, 'CODIGO_MH' => 'IQ', 'NOMBREPAIS' => 'Irak'],
            ['ID_PAIS' => 98, 'CODIGO_MH' => 'IE', 'NOMBREPAIS' => 'Irlanda'],
            ['ID_PAIS' => 99, 'CODIGO_MH' => 'BV', 'NOMBREPAIS' => 'Isla Bouvet'],
            ['ID_PAIS' => 100, 'CODIGO_MH' => 'IM', 'NOMBREPAIS' => 'Isla de Man'],
            ['ID_PAIS' => 101, 'CODIGO_MH' => 'NF', 'NOMBREPAIS' => 'Isla Norfolk'],
            ['ID_PAIS' => 102, 'CODIGO_MH' => 'IS', 'NOMBREPAIS' => 'Islandia'],
            ['ID_PAIS' => 103, 'CODIGO_MH' => 'CX', 'NOMBREPAIS' => 'Islas Navidad'],
            ['ID_PAIS' => 104, 'CODIGO_MH' => 'CC', 'NOMBREPAIS' => 'Islas Cocos'],
            ['ID_PAIS' => 105, 'CODIGO_MH' => 'CK', 'NOMBREPAIS' => 'Islas Cook'],
            ['ID_PAIS' => 106, 'CODIGO_MH' => 'FO', 'NOMBREPAIS' => 'Islas Faroe'],
            ['ID_PAIS' => 107, 'CODIGO_MH' => 'GS', 'NOMBREPAIS' => 'Islas Georgias d. S.-Sandwich d. S.'],
            ['ID_PAIS' => 108, 'CODIGO_MH' => 'HM', 'NOMBREPAIS' => 'Islas Heard y McDonald'],
            ['ID_PAIS' => 109, 'CODIGO_MH' => 'FK', 'NOMBREPAIS' => 'Islas Malvinas (Falkland)'],
            ['ID_PAIS' => 110, 'CODIGO_MH' => 'MP', 'NOMBREPAIS' => 'Islas Marianas del Norte'],
            ['ID_PAIS' => 111, 'CODIGO_MH' => 'MH', 'NOMBREPAIS' => 'Islas Marshall'],
            ['ID_PAIS' => 112, 'CODIGO_MH' => 'PN', 'NOMBREPAIS' => 'Islas Pitcairn'],
            ['ID_PAIS' => 113, 'CODIGO_MH' => 'TC', 'NOMBREPAIS' => 'Islas Turcas y Caicos'],
            ['ID_PAIS' => 114, 'CODIGO_MH' => 'UM', 'NOMBREPAIS' => 'Islas Ultramarinas de E.E.U.U'],
            ['ID_PAIS' => 115, 'CODIGO_MH' => 'VI', 'NOMBREPAIS' => 'Islas Vírgenes'],
            ['ID_PAIS' => 116, 'CODIGO_MH' => 'IL', 'NOMBREPAIS' => 'Israel'],
            ['ID_PAIS' => 117, 'CODIGO_MH' => 'IT', 'NOMBREPAIS' => 'Italia'],
            ['ID_PAIS' => 118, 'CODIGO_MH' => 'JM', 'NOMBREPAIS' => 'Jamaica'],
            ['ID_PAIS' => 119, 'CODIGO_MH' => 'JP', 'NOMBREPAIS' => 'Japón'],
            ['ID_PAIS' => 120, 'CODIGO_MH' => 'JE', 'NOMBREPAIS' => 'Jersey'],
            ['ID_PAIS' => 121, 'CODIGO_MH' => 'JO', 'NOMBREPAIS' => 'Jordania'],
            ['ID_PAIS' => 122, 'CODIGO_MH' => 'KZ', 'NOMBREPAIS' => 'Kazajistán'],
            ['ID_PAIS' => 123, 'CODIGO_MH' => 'KE', 'NOMBREPAIS' => 'Kenia'],
            ['ID_PAIS' => 124, 'CODIGO_MH' => 'KG', 'NOMBREPAIS' => 'Kirguistán'],
            ['ID_PAIS' => 125, 'CODIGO_MH' => 'KI', 'NOMBREPAIS' => 'Kiribati'],
            ['ID_PAIS' => 126, 'CODIGO_MH' => 'KW', 'NOMBREPAIS' => 'Kuwait'],
            ['ID_PAIS' => 127, 'CODIGO_MH' => 'LA', 'NOMBREPAIS' => 'Laos, República Democrática'],
            ['ID_PAIS' => 128, 'CODIGO_MH' => 'LS', 'NOMBREPAIS' => 'Lesotho'],
            ['ID_PAIS' => 129, 'CODIGO_MH' => 'LV', 'NOMBREPAIS' => 'Letonia'],
            ['ID_PAIS' => 130, 'CODIGO_MH' => 'LB', 'NOMBREPAIS' => 'Líbano'],
            ['ID_PAIS' => 131, 'CODIGO_MH' => 'LR', 'NOMBREPAIS' => 'Liberia'],
            ['ID_PAIS' => 132, 'CODIGO_MH' => 'LY', 'NOMBREPAIS' => 'Libia'],
            ['ID_PAIS' => 133, 'CODIGO_MH' => 'LI', 'NOMBREPAIS' => 'Liechtenstein'],
            ['ID_PAIS' => 134, 'CODIGO_MH' => 'LT', 'NOMBREPAIS' => 'Lituania'],
            ['ID_PAIS' => 135, 'CODIGO_MH' => 'LU', 'NOMBREPAIS' => 'Luxemburgo'],
            ['ID_PAIS' => 136, 'CODIGO_MH' => 'MO', 'NOMBREPAIS' => 'Macao'],
            ['ID_PAIS' => 137, 'CODIGO_MH' => 'MK', 'NOMBREPAIS' => 'Macedonia'],
            ['ID_PAIS' => 138, 'CODIGO_MH' => 'MG', 'NOMBREPAIS' => 'Madagascar'],
            ['ID_PAIS' => 139, 'CODIGO_MH' => 'MY', 'NOMBREPAIS' => 'Malasia'],
            ['ID_PAIS' => 140, 'CODIGO_MH' => 'MW', 'NOMBREPAIS' => 'Malawi'],
            ['ID_PAIS' => 141, 'CODIGO_MH' => 'MV', 'NOMBREPAIS' => 'Maldivas'],
            ['ID_PAIS' => 142, 'CODIGO_MH' => 'ML', 'NOMBREPAIS' => 'Malí'],
            ['ID_PAIS' => 143, 'CODIGO_MH' => 'MT', 'NOMBREPAIS' => 'Malta'],
            ['ID_PAIS' => 144, 'CODIGO_MH' => 'MA', 'NOMBREPAIS' => 'Marruecos'],
            ['ID_PAIS' => 145, 'CODIGO_MH' => 'MQ', 'NOMBREPAIS' => 'Martinica e.a.'],
            ['ID_PAIS' => 146, 'CODIGO_MH' => 'MU', 'NOMBREPAIS' => 'Mauricio'],
            ['ID_PAIS' => 147, 'CODIGO_MH' => 'MR', 'NOMBREPAIS' => 'Mauritania'],
            ['ID_PAIS' => 148, 'CODIGO_MH' => 'YT', 'NOMBREPAIS' => 'Mayotte'],
            ['ID_PAIS' => 149, 'CODIGO_MH' => 'MX', 'NOMBREPAIS' => 'México'],
            ['ID_PAIS' => 150, 'CODIGO_MH' => 'FM', 'NOMBREPAIS' => 'Micronesia'],
            ['ID_PAIS' => 151, 'CODIGO_MH' => 'MD', 'NOMBREPAIS' => 'Moldavia, República de'],
            ['ID_PAIS' => 152, 'CODIGO_MH' => 'MC', 'NOMBREPAIS' => 'Mónaco'],
            ['ID_PAIS' => 153, 'CODIGO_MH' => 'MN', 'NOMBREPAIS' => 'Mongolia'],
            ['ID_PAIS' => 154, 'CODIGO_MH' => 'ME', 'NOMBREPAIS' => 'Montenegro'],
            ['ID_PAIS' => 155, 'CODIGO_MH' => 'MS', 'NOMBREPAIS' => 'Montserrat'],
            ['ID_PAIS' => 156, 'CODIGO_MH' => 'MZ', 'NOMBREPAIS' => 'Mozambique'],
            ['ID_PAIS' => 157, 'CODIGO_MH' => 'MM', 'NOMBREPAIS' => 'Myanmar'],
            ['ID_PAIS' => 158, 'CODIGO_MH' => 'NA', 'NOMBREPAIS' => 'Namibia'],
            ['ID_PAIS' => 159, 'CODIGO_MH' => 'NR', 'NOMBREPAIS' => 'Nauru'],
            ['ID_PAIS' => 160, 'CODIGO_MH' => 'NP', 'NOMBREPAIS' => 'Nepal'],
            ['ID_PAIS' => 161, 'CODIGO_MH' => 'NI', 'NOMBREPAIS' => 'Nicaragua'],
            ['ID_PAIS' => 162, 'CODIGO_MH' => 'NE', 'NOMBREPAIS' => 'Níger'],
            ['ID_PAIS' => 163, 'CODIGO_MH' => 'NG', 'NOMBREPAIS' => 'Nigeria'],
            ['ID_PAIS' => 164, 'CODIGO_MH' => 'NU', 'NOMBREPAIS' => 'Niue'],
            ['ID_PAIS' => 165, 'CODIGO_MH' => 'NO', 'NOMBREPAIS' => 'Noruega'],
            ['ID_PAIS' => 166, 'CODIGO_MH' => 'NC', 'NOMBREPAIS' => 'Nueva Caledonia'],
            ['ID_PAIS' => 167, 'CODIGO_MH' => 'NZ', 'NOMBREPAIS' => 'Nueva Zelanda'],
            ['ID_PAIS' => 168, 'CODIGO_MH' => 'OM', 'NOMBREPAIS' => 'Omán'],
            ['ID_PAIS' => 169, 'CODIGO_MH' => 'NL', 'NOMBREPAIS' => 'Países Bajos'],
            ['ID_PAIS' => 170, 'CODIGO_MH' => 'PK', 'NOMBREPAIS' => 'Pakistán'],
            ['ID_PAIS' => 171, 'CODIGO_MH' => 'PW', 'NOMBREPAIS' => 'Palaos'],
            ['ID_PAIS' => 172, 'CODIGO_MH' => 'PS', 'NOMBREPAIS' => 'Palestina'],
            ['ID_PAIS' => 173, 'CODIGO_MH' => 'PA', 'NOMBREPAIS' => 'Panamá'],
            ['ID_PAIS' => 174, 'CODIGO_MH' => 'PG', 'NOMBREPAIS' => 'Papúa, Nueva Guinea'],
            ['ID_PAIS' => 175, 'CODIGO_MH' => 'PY', 'NOMBREPAIS' => 'Paraguay'],
            ['ID_PAIS' => 176, 'CODIGO_MH' => 'PE', 'NOMBREPAIS' => 'Perú'],
            ['ID_PAIS' => 177, 'CODIGO_MH' => 'PF', 'NOMBREPAIS' => 'Polinesia Francesa'],
            ['ID_PAIS' => 178, 'CODIGO_MH' => 'PL', 'NOMBREPAIS' => 'Polonia'],
            ['ID_PAIS' => 179, 'CODIGO_MH' => 'PT', 'NOMBREPAIS' => 'Portugal'],
            ['ID_PAIS' => 180, 'CODIGO_MH' => 'PR', 'NOMBREPAIS' => 'Puerto Rico'],
            ['ID_PAIS' => 181, 'CODIGO_MH' => 'QA', 'NOMBREPAIS' => 'Qatar'],
            ['ID_PAIS' => 182, 'CODIGO_MH' => 'GB', 'NOMBREPAIS' => 'Reino Unido'],
            ['ID_PAIS' => 183, 'CODIGO_MH' => 'KP', 'NOMBREPAIS' => 'Rep. Democrática popular de Corea'],
            ['ID_PAIS' => 184, 'CODIGO_MH' => 'CZ', 'NOMBREPAIS' => 'República Checa'],
            ['ID_PAIS' => 185, 'CODIGO_MH' => 'KR', 'NOMBREPAIS' => 'República de Corea'],
            ['ID_PAIS' => 186, 'CODIGO_MH' => 'CD', 'NOMBREPAIS' => 'República Democrática del Congo'],
            ['ID_PAIS' => 187, 'CODIGO_MH' => 'DO', 'NOMBREPAIS' => 'República Dominicana'],
            ['ID_PAIS' => 188, 'CODIGO_MH' => 'IR', 'NOMBREPAIS' => 'República Islámica de Irán'],
            ['ID_PAIS' => 189, 'CODIGO_MH' => 'RE', 'NOMBREPAIS' => 'Reunión'],
            ['ID_PAIS' => 190, 'CODIGO_MH' => 'RW', 'NOMBREPAIS' => 'Ruanda'],
            ['ID_PAIS' => 191, 'CODIGO_MH' => 'RO', 'NOMBREPAIS' => 'Rumania'],
            ['ID_PAIS' => 192, 'CODIGO_MH' => 'RU', 'NOMBREPAIS' => 'Rusia'],
            ['ID_PAIS' => 193, 'CODIGO_MH' => 'EH', 'NOMBREPAIS' => 'Sahara Occidental'],
            ['ID_PAIS' => 194, 'CODIGO_MH' => 'BL', 'NOMBREPAIS' => 'Saint Barthélemy'],
            ['ID_PAIS' => 195, 'CODIGO_MH' => 'MF', 'NOMBREPAIS' => 'Saint Martin (French part)'],
            ['ID_PAIS' => 196, 'CODIGO_MH' => 'SB', 'NOMBREPAIS' => 'Salomón, Islas'],
            ['ID_PAIS' => 197, 'CODIGO_MH' => 'WS', 'NOMBREPAIS' => 'Samoa'],
            ['ID_PAIS' => 198, 'CODIGO_MH' => 'AS', 'NOMBREPAIS' => 'Samoa Americana'],
            ['ID_PAIS' => 199, 'CODIGO_MH' => 'KN', 'NOMBREPAIS' => 'San Cristóbal y Nieves'],
            ['ID_PAIS' => 200, 'CODIGO_MH' => 'SM', 'NOMBREPAIS' => 'San Marino'],
            ['ID_PAIS' => 201, 'CODIGO_MH' => 'PM', 'NOMBREPAIS' => 'San Pedro y Miquelón'],
            ['ID_PAIS' => 202, 'CODIGO_MH' => 'VC', 'NOMBREPAIS' => 'San Vicente y las Granadinas'],
            ['ID_PAIS' => 203, 'CODIGO_MH' => 'SH', 'NOMBREPAIS' => 'Santa Elena'],
            ['ID_PAIS' => 204, 'CODIGO_MH' => 'LC', 'NOMBREPAIS' => 'Santa Lucía'],
            ['ID_PAIS' => 205, 'CODIGO_MH' => 'ST', 'NOMBREPAIS' => 'Santo Tomé y Príncipe'],
            ['ID_PAIS' => 206, 'CODIGO_MH' => 'SN', 'NOMBREPAIS' => 'Senegal'],
            ['ID_PAIS' => 207, 'CODIGO_MH' => 'RS', 'NOMBREPAIS' => 'Serbia'],
            ['ID_PAIS' => 208, 'CODIGO_MH' => 'SC', 'NOMBREPAIS' => 'Seychelles'],
            ['ID_PAIS' => 209, 'CODIGO_MH' => 'SL', 'NOMBREPAIS' => 'Sierra Leona'],
            ['ID_PAIS' => 210, 'CODIGO_MH' => 'SG', 'NOMBREPAIS' => 'Singapur'],
            ['ID_PAIS' => 211, 'CODIGO_MH' => 'SX', 'NOMBREPAIS' => 'Sint Maarten (Dutch part)'],
            ['ID_PAIS' => 212, 'CODIGO_MH' => 'SY', 'NOMBREPAIS' => 'Siria'],
            ['ID_PAIS' => 213, 'CODIGO_MH' => 'SO', 'NOMBREPAIS' => 'Somalia'],
            ['ID_PAIS' => 214, 'CODIGO_MH' => 'SS', 'NOMBREPAIS' => 'South Sudan'],
            ['ID_PAIS' => 215, 'CODIGO_MH' => 'LK', 'NOMBREPAIS' => 'Sri Lanka'],
            ['ID_PAIS' => 216, 'CODIGO_MH' => 'ZA', 'NOMBREPAIS' => 'Sudáfrica'],
            ['ID_PAIS' => 217, 'CODIGO_MH' => 'SD', 'NOMBREPAIS' => 'Sudán'],
            ['ID_PAIS' => 218, 'CODIGO_MH' => 'SE', 'NOMBREPAIS' => 'Suecia'],
            ['ID_PAIS' => 219, 'CODIGO_MH' => 'CH', 'NOMBREPAIS' => 'Suiza'],
            ['ID_PAIS' => 220, 'CODIGO_MH' => 'SR', 'NOMBREPAIS' => 'Surinám'],
            ['ID_PAIS' => 221, 'CODIGO_MH' => 'SJ', 'NOMBREPAIS' => 'Svalbard y Jan Mayen'],
            ['ID_PAIS' => 222, 'CODIGO_MH' => 'SZ', 'NOMBREPAIS' => 'Swazilandia'],
            ['ID_PAIS' => 223, 'CODIGO_MH' => 'TH', 'NOMBREPAIS' => 'Tailandia'],
            ['ID_PAIS' => 224, 'CODIGO_MH' => 'TW', 'NOMBREPAIS' => 'Taiwan, Provincia de China'],
            ['ID_PAIS' => 225, 'CODIGO_MH' => 'TZ', 'NOMBREPAIS' => 'Tanzania, República Unida de'],
            ['ID_PAIS' => 226, 'CODIGO_MH' => 'TJ', 'NOMBREPAIS' => 'Tayikistán'],
            ['ID_PAIS' => 227, 'CODIGO_MH' => 'IO', 'NOMBREPAIS' => 'Territorio Británico Océano Indico'],
            ['ID_PAIS' => 228, 'CODIGO_MH' => 'TF', 'NOMBREPAIS' => 'Territorios Australes Franceses'],
            ['ID_PAIS' => 229, 'CODIGO_MH' => 'TL', 'NOMBREPAIS' => 'Timor Oriental'],
            ['ID_PAIS' => 230, 'CODIGO_MH' => 'TG', 'NOMBREPAIS' => 'Togo'],
            ['ID_PAIS' => 231, 'CODIGO_MH' => 'TK', 'NOMBREPAIS' => 'Tokelau'],
            ['ID_PAIS' => 232, 'CODIGO_MH' => 'TO', 'NOMBREPAIS' => 'Tonga'],
            ['ID_PAIS' => 233, 'CODIGO_MH' => 'TT', 'NOMBREPAIS' => 'Trinidad y Tobago'],
            ['ID_PAIS' => 234, 'CODIGO_MH' => 'TN', 'NOMBREPAIS' => 'Túnez'],
            ['ID_PAIS' => 235, 'CODIGO_MH' => 'TM', 'NOMBREPAIS' => 'Turkmenistán'],
            ['ID_PAIS' => 236, 'CODIGO_MH' => 'TR', 'NOMBREPAIS' => 'Turquía'],
            ['ID_PAIS' => 237, 'CODIGO_MH' => 'TV', 'NOMBREPAIS' => 'Tuvalu'],
            ['ID_PAIS' => 238, 'CODIGO_MH' => 'UA', 'NOMBREPAIS' => 'Ucrania'],
            ['ID_PAIS' => 239, 'CODIGO_MH' => 'UG', 'NOMBREPAIS' => 'Uganda'],
            ['ID_PAIS' => 240, 'CODIGO_MH' => 'UY', 'NOMBREPAIS' => 'Uruguay'],
            ['ID_PAIS' => 241, 'CODIGO_MH' => 'UZ', 'NOMBREPAIS' => 'Uzbekistán'],
            ['ID_PAIS' => 242, 'CODIGO_MH' => 'VU', 'NOMBREPAIS' => 'Vanuatu'],
            ['ID_PAIS' => 243, 'CODIGO_MH' => 'VE', 'NOMBREPAIS' => 'Venezuela'],
            ['ID_PAIS' => 244, 'CODIGO_MH' => 'VN', 'NOMBREPAIS' => 'Vietnam'],
            ['ID_PAIS' => 245, 'CODIGO_MH' => 'VG', 'NOMBREPAIS' => 'Islas Vírgenes Británicas'],
            ['ID_PAIS' => 246, 'CODIGO_MH' => 'WF', 'NOMBREPAIS' => 'Wallis y Fortuna, Islas'],
            ['ID_PAIS' => 247, 'CODIGO_MH' => 'YE', 'NOMBREPAIS' => 'Yemen'],
            ['ID_PAIS' => 248, 'CODIGO_MH' => 'ZM', 'NOMBREPAIS' => 'Zambia'],
            ['ID_PAIS' => 249, 'CODIGO_MH' => 'ZW', 'NOMBREPAIS' => 'Zimbabue'],
        ];

        DB::table('PAIS')->upsert($paises, ['ID_PAIS'], ['CODIGO_MH', 'NOMBREPAIS']);

        Schema::enableForeignKeyConstraints();
    }
}
